//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class property
    {
        public int id { get; set; }
        public string location { get; set; }
        public decimal price { get; set; }
        public Nullable<int> beds { get; set; }
        public Nullable<decimal> sqft { get; set; }
        public Nullable<decimal> lot_size { get; set; }
    }
}
